### ISSUE TITLE
No response on the PC or web version of Telegram

### ISSUE THREAD

**Issue by kennysin1444** [TownSquareXYZ/tonconnect-ui-vue#6]
It works easily when using the ui-vue version. Thank you.

However, while it works fine on mobile and Web, It doesn't return to the mini-app when clicking the connect button on the Mac version of Telegram.

**Comment by cici090** [comment]
> It works easily when using the ui-vue version. Thank you.
> 
> However, while it works fine on mobile and Web, It doesn't return to the mini-app when clicking the connect button on the �Mac version of Telegram.

We are glad to know that it worked well for you and thank you for your feedback.😄
To connect to Telegram, it may also need the TMA SDK to work with, we are preparing TON Connect User Interface (UI) for Vue applications, please look forward to it.😊

**Comment by cici090** [comment]
> It works easily when using the ui-vue version. Thank you.
> 
> However, while it works fine on mobile and Web, It doesn't return to the mini-app when clicking the connect button on the �Mac version of Telegram.

We are glad to know that it worked well for you and thank you for your feedback.😄
Regarding your mention of the Telegram for Mac desktop connect button not working, we have tested it and found that it can work at this time. Please try again and see if there are any other factors influencing this. If the problem still exists, please provide more detailed information so that we can better troubleshoot and solve the problem for you!
![image](https://github.com/user-attachments/assets/03c240cb-ce2c-4940-9a04-4d5a92a027e9)
